// agent-dir.test.mjs — agent-directory resolution in permission_gate, notify and check_git_extensions.
//
// Run: node --test tests/agent-dir.test.mjs     (Node >= 22.19, no dependencies, no network, no pty)
//
// Every extension resolves the agent dir once at module load (the value is a module-level const), so
// each environment case needs its own node process: changing the env after import has no effect.
// Assertions read the `/permission-gate` message and the files that get written, because a
// "no warning" check would also pass when the extension fails to load at all.
//
// The pi-side contract pinned down here, read from pi's dist in 1.0.4 and 1.1.0 (dist/config.js
// `getAgentDir`, `ENV_AGENT_DIR` derived from the package's app name):
//   - PI_CODING_AGENT_DIR wins only when it is truthy, and is tilde-expanded
//   - the empty string is not a directory value, and TAU_CODING_AGENT_DIR is never read
//   - otherwise the directory is <home>/.pi/agent
// The extensions call pi's own `getAgentDir()` for this, so the test has to give plain node the same
// alias pi's extension loader gives them (dist/core/extensions/loader.js `getAliases`, and
// dist/core/extensions/virtual-modules.js in compiled builds). That alias is generated below.

import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { delimiter, dirname, join } from "node:path";
import { tmpdir } from "node:os";
import { fileURLToPath, pathToFileURL } from "node:url";

const EXT = join(dirname(fileURLToPath(import.meta.url)), "..", "extensions");
const PI_HOOKS_PINNED = "git:github.com/prateekmedia/pi-hooks@1.0.2";
const PI_PACKAGE = "@earendil-works/pi-coding-agent";

const root = mkdtempSync(join(tmpdir(), "pi-agent-dir-"));
let probeCount = 0;
const HOME_DIR = join(root, "home");
const HOME_AGENT = join(HOME_DIR, ".pi", "agent");
const DECOY_CWD = join(root, "decoy-cwd");
const EMPTY_PATH_DIR = join(root, "empty-path");
const TILDE_AGENT = "tilde-agent";

for (const dir of [HOME_DIR, HOME_AGENT, DECOY_CWD, EMPTY_PATH_DIR]) mkdirSync(dir, { recursive: true });

// The four agent dirs under test, each with a distinctive level/threshold pair so an assertion can
// tell which file was actually read.
const ENV_PG = join(root, "env-permission-gate");
const ENV_NOTIFY = join(root, "env-notify");
const ENV_CHECK = join(root, "env-check");
const TAU_AGENT = join(root, "tau-agent");

/** Writes the settings.json that permission_gate reports on. */
function writeSettings(agentDir, { level, threshold = "low", pin = PI_HOOKS_PINNED }) {
  mkdirSync(agentDir, { recursive: true });
  writeFileSync(
    join(agentDir, "settings.json"),
    JSON.stringify({
      packages: [{ source: pin, extensions: ["permission/permission.ts"] }],
      permissionLevel: level,
      permissionGate: { threshold, gate: true },
    }),
  );
}

writeSettings(ENV_PG, { level: "high", threshold: "high" });
writeSettings(ENV_NOTIFY, { level: "high", threshold: "high" });
writeSettings(ENV_CHECK, { level: "high", threshold: "high" });
writeSettings(HOME_AGENT, { level: "low" });
writeSettings(TAU_AGENT, { level: "bypassed" });
writeSettings(join(HOME_DIR, TILDE_AGENT), { level: "high", threshold: "high" });
writeSettings(DECOY_CWD, { level: "high", threshold: "high" }); // must never be read: it is cwd, not the agent dir

/** Finds the pi package the same way the loader comes from, and writes the alias hook for plain node. */
function findPiPackage() {
  const candidates = [];
  if (process.env.PI_TEST_PACKAGE) candidates.push(process.env.PI_TEST_PACKAGE);
  for (const entry of (process.env.PATH ?? "").split(delimiter).filter(Boolean)) {
    candidates.push(join(entry, "node_modules", PI_PACKAGE));
  }
  if (process.env.APPDATA) candidates.push(join(process.env.APPDATA, "npm", "node_modules", PI_PACKAGE));
  candidates.push("/usr/local/lib/node_modules/" + PI_PACKAGE);
  try {
    const npmRoot = execFileSync("npm", ["root", "-g"], { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
    candidates.push(join(npmRoot.trim(), PI_PACKAGE));
  } catch {
    // npm missing: the candidates above are enough
  }
  const found = candidates.find((dir) => existsSync(join(dir, "dist", "index.js")));
  assert.ok(
    found,
    `cannot locate ${PI_PACKAGE}; set PI_TEST_PACKAGE to its install directory`,
  );
  return found;
}

const hookPath = join(root, "pi-alias-hooks.mjs");
writeFileSync(
  hookPath,
  [
    "// Generated by agent-dir.test.mjs: the alias pi's own extension loader applies.",
    'import { registerHooks } from "node:module";',
    `const entry = ${JSON.stringify(pathToFileURL(join(findPiPackage(), "dist", "index.js")).href)};`,
    "registerHooks({",
    "  resolve(specifier, context, nextResolve) {",
    `    if (specifier === ${JSON.stringify(PI_PACKAGE)}) return { url: entry, shortCircuit: true };`,
    "    return nextResolve(specifier, context);",
    "  },",
    "});",
    "",
  ].join("\n"),
);

/** Environment for one case: a fake home, no inherited agent-dir variables. */
function childEnv({ agentDir, tauDir, home = HOME_DIR, path: pathValue } = {}) {
  const env = { ...process.env, HOME: home, USERPROFILE: home };
  delete env.PI_CODING_AGENT_DIR;
  delete env.TAU_CODING_AGENT_DIR;
  if (agentDir !== undefined) env.PI_CODING_AGENT_DIR = agentDir;
  if (tauDir !== undefined) env.TAU_CODING_AGENT_DIR = tauDir;
  if (pathValue !== undefined) env.PATH = pathValue;
  return env;
}

/** Runs a probe in a fresh node process and returns the JSON it printed. */
function runProbe(body, env, cwd = root) {
  // The probe goes into a file rather than into --eval: the code stays out of argv (execed
  // arguments are re-parsed by the Windows CRT, which mangles embedded quotes).
  const probePath = join(root, `probe-${(probeCount += 1)}.mjs`);
  writeFileSync(probePath, `${body}\nconsole.log('PROBE ' + JSON.stringify(result));\n`);
  let stdout;
  try {
    stdout = execFileSync(
      process.execPath,
      ["--import", pathToFileURL(hookPath).href, probePath],
      { cwd, env, encoding: "utf8", timeout: 30_000, stdio: ["ignore", "pipe", "pipe"] },
    );
  } catch (error) {
    throw new Error(`probe failed (${error.status ?? "signal"}):\n${error.stdout ?? ""}\n${error.stderr ?? ""}`);
  }
  const line = stdout.split(/\r?\n/).find((entry) => entry.startsWith("PROBE "));
  assert.ok(line, `probe printed no result:\n${stdout}`);
  return JSON.parse(line.slice("PROBE ".length));
}

function extensionUrl(file) {
  return pathToFileURL(join(EXT, file)).href;
}

/** Loads permission_gate and returns what `/permission-gate` reports. */
function permissionGateResult(env, cwd = root) {
  return runProbe(
    [
      `const ext = await import(${JSON.stringify(extensionUrl("permission_gate.ts"))});`,
      "const handlers = {};",
      "const commands = {};",
      "const pi = {",
      "  on(event, handler) { (handlers[event] ??= []).push(handler); },",
      "  registerCommand(name, command) { commands[name] = command; },",
      "  registerTool() {},",
      "  addFlag() {},",
      "};",
      "ext.default(pi);",
      "const notes = [];",
      "const ctx = {",
      "  mode: 'tui',",
      "  hasUI: true,",
      "  ui: {",
      "    notify: (message, level) => notes.push(level + ': ' + message),",
      "    setStatus() {},",
      "    select: async () => 'continue',",
      "  },",
      "};",
      "handlers.session_start[0]({ type: 'session_start' }, ctx);",
      "await commands['permission-gate'].handler('', ctx);",
      "const result = { notes, level: notes.join(' ').match(/level=([a-z]+)/)?.[1] ?? null, drift: notes.join(' ').includes('no entry in packages') };",
    ].join("\n"),
    env,
    cwd,
  );
}

function runCommand(file, command, args, env, cwd = root) {
  return runProbe(
    [
      `const ext = await import(${JSON.stringify(extensionUrl(file))});`,
      "const commands = {};",
      "const pi = {",
      "  on() {},",
      "  registerCommand(name, handler) { commands[name] = handler; },",
      "  registerTool() {},",
      "  addFlag() {},",
      "};",
      "ext.default(pi);",
      "const notes = [];",
      "const ctx = { mode: 'tui', hasUI: true, ui: { notify: (message) => notes.push(message), setStatus() {}, select: async () => 'continue' } };",
      `await commands[${JSON.stringify(command)}].handler(${JSON.stringify(args)}, ctx);`,
      "const result = { notes };",
    ].join("\n"),
    env,
    cwd,
  );
}

test("reads settings.json from PI_CODING_AGENT_DIR", () => {
  const result = permissionGateResult(childEnv({ agentDir: ENV_PG }));
  assert.equal(result.level, "high", result.notes.join(" | "));
  assert.match(result.notes.join(" "), /pin 1\.0\.2 \(verified\)/);
  assert.equal(result.drift, false, result.notes.join(" | "));
});

test("falls back to <home>/.pi/agent when the variable is unset", () => {
  const result = permissionGateResult(childEnv({}));
  assert.equal(result.level, "low", result.notes.join(" | "));
  assert.equal(result.drift, false, result.notes.join(" | "));
});

test("treats an empty variable as unset, like pi's truthy check", () => {
  // cwd holds a decoy settings.json: reading a cwd-relative path here would report level=high.
  const result = permissionGateResult(childEnv({ agentDir: "" }), DECOY_CWD);
  assert.equal(result.level, "low", result.notes.join(" | "));
  assert.equal(result.drift, false, result.notes.join(" | "));
});

test("expands a tilde in the variable, like pi does", () => {
  const result = permissionGateResult(childEnv({ agentDir: `~/${TILDE_AGENT}` }));
  assert.equal(result.level, "high", result.notes.join(" | "));
  assert.equal(result.drift, false, result.notes.join(" | "));
});

test("ignores TAU_CODING_AGENT_DIR (a name pi never reads)", () => {
  const result = permissionGateResult(childEnv({ tauDir: TAU_AGENT }));
  assert.equal(result.level, "low", result.notes.join(" | "));
  assert.doesNotMatch(result.notes.join(" "), /bypassed/);
});

test("notify writes its config into the agent dir", () => {
  runCommand("notify.ts", "notify", "on", childEnv({ agentDir: ENV_NOTIFY }));
  assert.equal(existsSync(join(ENV_NOTIFY, "notify-config.json")), true);
  assert.equal(existsSync(join(HOME_AGENT, "notify-config.json")), false);
});

test("check_git_extensions writes its report into the agent dir", () => {
  // Empty PATH: every `git ls-remote` fails fast, so the report is written without network access.
  runCommand("check_git_extensions.ts", "check_git_extensions", "", childEnv({ agentDir: ENV_CHECK, path: EMPTY_PATH_DIR }));
  assert.equal(existsSync(join(ENV_CHECK, "data", "git-extension-check.md")), true);
  assert.equal(existsSync(join(HOME_AGENT, "data")), false);
});

test("extensions resolve the agent dir through pi, not homedir()", () => {
  const offenders = readdirSync(EXT)
    .filter((file) => file.endsWith(".ts"))
    .filter((file) => readFileSync(join(EXT, file), "utf8").includes("homedir()"));
  assert.deepEqual(offenders, [], "use pi's getAgentDir() instead of homedir()");
});
